### ISSUE TITLE
Issue with button icon color on Mojave

### ISSUE THREAD

**Issue by NicolasGrimonpont** [Obbut/iCloud-Control#8]
The control button in the finder does not support the dark mojave mode. The color of the icon should change to white.

**Comment by Endilus** [comment]
Having the same issue 😢
Would be really nice with white icon so it fits dark mode.

**Comment by Gevoraway** [comment]
Agree. The icon needs to be updated to match Mojave dark mode

**Comment by joakimhew** [comment]
@NicolasGrimonpont @Endilus @Gevoraway @zzxjohn 

While we're waiting for Obbut to support this I've made a release that fixes this in the meantime 😀
Just download and replace your current iCloud Control app with the following: 

[1.1.0-dark-mode-support](https://github.com/joakimhew/iCloud-Control/releases/tag/1.1.0-dark-mode-support)

Don't forget to relaunch finder when you switch between light mode and dark mode. 
Cheers!

**Comment by toadle** [comment]
@NicolasGrimonpont @Endilus @Gevoraway @zzxjohn @joakimhew 

Wow this app is a live-safer. Also having dark-mode support is great.
Would you guys be interested in to also add localization?

I could provide German.

**Comment by joakimhew** [comment]
@toadle I could possibly help with localization. Unfortunately I'm not the author of this repository and I'm not sure if the original maintainer is interested in help with it so for now it'll have to be my fork. 

@Obbut Would you be interested in adding me as a maintainer? I'd be happy to help keep it updated!

**Comment by Obbut** [comment]
Sorry, I've been quite busy so that's why I didn't reply earlier.

@joakimhew Thanks for your PR! I've merged it for now. I'll make a new release.

If you have ideas about improving this app and want to help, like adding more features like localization, I would be happy to discuss the options. Maybe the easiest way for that is to get in touch using a chat service. I'm reachable on the [OpenKitten Slack](https://launchpass.com/openkitten) (that's the Slack for some other Swift projects that I maintain), or on Telegram as @Obbut

**Comment by toadle** [comment]
@joakimhew BTW: There can be a problem after switching into Dark Mode that the icon stays in the color of the mode before. I noticed this while using https://nightowl.kramser.xyz/

**Comment by joakimhew** [comment]
@toadle Yup, I'm not sure why this happens as other icons in the finder are updated. But a simple relaunch of the finder should fix it.

`⎇ + right click ` on the finder, and then click relaunch 👍 

@Obbut I'll join your slack and we can have chat about it!
